ALTER TABLE user_profiles
    ADD COLUMN region_new enum(
    'SEOUL','BUSAN','DAEGU','INCHEON','GWANGJU','DAEJEON','ULSAN','SEJONG',
    'GYEONGGI','GANGWON','CHUNGBUK','CHUNGNAM','JEONBUK','JEONNAM','GYEONGBUK','GYEONGNAM','JEJU'
    ) NULL;

UPDATE user_profiles
SET region_new = CASE region
    WHEN '서울' THEN 'SEOUL' WHEN '서울특별시' THEN 'SEOUL'
    WHEN '부산' THEN 'BUSAN' WHEN '부산광역시' THEN 'BUSAN'
    WHEN '대구' THEN 'DAEGU' WHEN '대구광역시' THEN 'DAEGU'
    WHEN '인천' THEN 'INCHEON' WHEN '인천광역시' THEN 'INCHEON'
    WHEN '광주' THEN 'GWANGJU' WHEN '광주광역시' THEN 'GWANGJU'
    WHEN '대전' THEN 'DAEJEON' WHEN '대전광역시' THEN 'DAEJEON'
    WHEN '울산' THEN 'ULSAN' WHEN '울산광역시' THEN 'ULSAN'
    WHEN '세종' THEN 'SEJONG' WHEN '세종특별자치시' THEN 'SEJONG'
    WHEN '경기' THEN 'GYEONGGI' WHEN '경기도' THEN 'GYEONGGI'
    WHEN '강원' THEN 'GANGWON' WHEN '강원도' THEN 'GANGWON' WHEN '강원특별자치도' THEN 'GANGWON'
    WHEN '충북' THEN 'CHUNGBUK' WHEN '충청북도' THEN 'CHUNGBUK'
    WHEN '충남' THEN 'CHUNGNAM' WHEN '충청남도' THEN 'CHUNGNAM'
    WHEN '전북' THEN 'JEONBUK' WHEN '전라북도' THEN 'JEONBUK' WHEN '전북특별자치도' THEN 'JEONBUK'
    WHEN '전남' THEN 'JEONNAM' WHEN '전라남도' THEN 'JEONNAM'
    WHEN '경북' THEN 'GYEONGBUK' WHEN '경상북도' THEN 'GYEONGBUK'
    WHEN '경남' THEN 'GYEONGNAM' WHEN '경상남도' THEN 'GYEONGNAM'
    WHEN '제주' THEN 'JEJU' WHEN '제주도' THEN 'JEJU' WHEN '제주특별자치도' THEN 'JEJU'
    ELSE NULL
END
WHERE region IS NOT NULL;

ALTER TABLE user_profiles
    DROP COLUMN region;

ALTER TABLE user_profiles
    CHANGE COLUMN region_new region enum(
    'SEOUL','BUSAN','DAEGU','INCHEON','GWANGJU','DAEJEON','ULSAN','SEJONG',
    'GYEONGGI','GANGWON','CHUNGBUK','CHUNGNAM','JEONBUK','JEONNAM','GYEONGBUK','GYEONGNAM','JEJU'
    ) NULL;
