spring:
  datasource:
    url: jdbc:mysql://localhost:13306/my_project_db
    username: app
    password: app1234

  jpa:
    hibernate:
      ddl-auto: update # prod 환경에서 반드시 validate or none 으로 수정

    show-sql: true # jpa가 실행한 sql문 콘솔에 출력

    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

  data:
    redis:
      host: localhost
      port: 6379

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

ocr:
  google-vision-key-path: ${GCP_KEY_PATH:classpath:gcp-key.json}

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    com.team10.backend.domain.user.ocr: DEBUG
