spring:
  datasource:
    url: jdbc:mysql://localhost:13306/my_project_db
    username: app
    password: app1234

  jpa:
    hibernate:
      ddl-auto: update # prod 환경에서 반드시 validate or none 으로 수정

    show-sql: true # jpa가 실행한 sql문 콘솔에 출력

    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

  data:
    redis:
      host: localhost
      port: 6379

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

ocr:
  google-vision-key-path: ${GCP_KEY_PATH:classpath:gcp-key.json}

jwt:
  secret: ${JWT_SECRET:moneystory-dev-secret-key-must-be-at-least-32-characters-long!}
  access-token-expiration-seconds: 3600      # 1시간
  refresh-token-expiration-seconds: 604800   # 7일

codef:
  client-id: ${CODEF_CLIENT_ID:b631fd83-1aab-44a1-b3bd-f861179cdf47}
  client-secret: ${CODEF_CLIENT_SECRET:8e76891f-ff10-4a83-ba0c-ec4b2cbd8943}
  public-key: ${CODEF_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzvtHhUxMWqCSoQhLpjjPocR3/Dt2ryZx8pu6Z5jCYhkwKg5AktRXP+1VbixKh8OfVHaDhPZ8Daqpf3pi5zS/feyJZ9Nd8Qzdll6PZbl7opKbFy2QKH85aOwaMGdu6Zdq1fEXOOYTMkGBvPtGoF20lxNM0FdcZEFEFDilcfQkQ/q2mq78+ItjY6DUrIIHPYzKQh3M70cab7X6pvK0eBWIFTbtwBx5hvV0ftYZWWUxnGgK1IOjxOUqNpJrfz2YiN/NyybHXhdR/4fsLmiC2J7wymBTTC/q/4XVhLj6FM//svFigXBNDLl9uBi1LTeCiQQky+0xVy3J2KC3hBCPSSP1mQIDAQAB}  

portone:
  api-secret: ${PORTONE_API_SECRET:moneybuddy}
  store-id: ${PORTONE_STORE_ID:store-bb65e821-eeb0-4a12-bd80-4e036a770949}
  channel-key: ${PORTONE_CHANNEL_KEY:channel-key-bcd683d9-77a5-406d-866e-7262a8df00d0}

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    com.team10.backend.domain.user.ocr: DEBUG
