name: deploy

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "backend/**"

permissions:
  contents: read
  packages: write

jobs:
  build-image-and-push:
    runs-on: ubuntu-latest

    outputs:
      image: ghcr.io/${{ github.repository_owner }}/team10-backend:${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: application-secret.yml 생성
        run: |
          mkdir -p backend/src/main/resources
          echo "${{ secrets.APPLICATION_SECRET }}" \
          > backend/src/main/resources/application-secret.yml

      - name: Verify secret file
        run: |
          ls -al backend/src/main/resources
          head -5 backend/src/main/resources/application-secret.yml

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build JAR
        run: |
          cd backend
          ./gradlew bootJar --no-daemon

      - name: Verify built JAR
        run: |
          unzip -l backend/build/libs/*.jar | grep application
          unzip -l backend/build/libs/*.jar | grep application-secret

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: backend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/team10-backend:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/team10-backend:latest

      - name: Verify app.jar in image
        run: |
          docker create --name temp ghcr.io/${{ github.repository_owner }}/team10-backend:${{ github.sha }}
          docker cp temp:/app/app.jar .
          unzip -l app.jar | grep application
          unzip -l app.jar | grep application-secret
          docker rm temp
  

  deploy:
    needs: build-image-and-push
    runs-on: ubuntu-latest

    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: APP-DATA 인스턴스 조회
        id: instance
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances \
          --filters \
          "Name=tag:Name,Values=team10-app-data-ec2" \
          "Name=instance-state-name,Values=running" \
          --query "Reservations[*].Instances[*].InstanceId" \
          --output text)

          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

      - name: Deploy
        uses: peterkimzz/aws-ssm-send-command@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          instance-ids: ${{ env.INSTANCE_ID }}

          command: |
            export GHCR_USERNAME="${{ secrets.GHCR_USERNAME }}"
            export GHCR_TOKEN="${{ secrets.GHCR_TOKEN }}"

            bash /dockerProjects/app-data/deploy.sh \
              ghcr.io/${{ github.repository_owner }}/team10-backend:${{ github.sha }}